version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Build & Push Docker Image
          command: |
            docker build -t bharatsurya1128/flask-devops-assignment:latest .
            docker push bharatsurya1128/flask-devops-assignment:latest

workflows:
  build_and_push:
    jobs:
      - build
